(in-package #:ski)

(defun prompt-for-input ()
  (format t "~&>>> ")
  (finish-output)
  (read-line t nil))

(defmacro with-driver-loop ((line-variable) &body body)
  (let ((condition-variable (gensym)))
    `(loop for ,line-variable = (prompt-for-input)
           while ,line-variable
           when (plusp (length ,line-variable))
             do (handler-case (progn ,@body)
                  (error (,condition-variable) (princ ,condition-variable))))))

(defun lambda-driver-loop ()
  "A REPL for lambda calculus."
  (let ((bindings (make-array 0 :adjustable t :fill-pointer t)))
    (with-driver-loop (input)
      (let ((thing (parse-lambda-input input)))
        (if (lambda-binding-p thing)
            (let* ((name-of-thing (name thing))
                   (i (position name-of-thing bindings :key #'name :test #'string=)))
              (if i (setf (aref bindings i) thing) (vector-push-extend thing bindings))
              (format t "~&~:[Created~;Updated~] binding ~a." i name-of-thing))
            (let ((term (substitute-lambda-bindings thing bindings)))
              (print-term (reduce-term term))))))))

(defun combinator-driver-loop ()
  "A REPL for combinatory logic."
  (let ((*combinator-bindings* (make-hash-table :test #'equal)))
    (with-driver-loop (input)
      (let ((thing (parse-combinator-input input)))
        (if (combinator-binding-p thing)
            (let* ((name-of-thing (name thing))
                   (present-p (nth-value 1 (gethash name-of-thing *combinator-bindings*))))
              (setf (gethash name-of-thing *combinator-bindings*) thing)
              (format t "~&~:[Created~;Updated~] binding ~a." present-p name-of-thing))
            (print-term (reduce-term thing)))))))

(defun substitute-lambda-bindings (term bindings)
  (loop for i from (1- (length bindings)) downto 0
        for binding = (aref bindings i)
        for var = (make-lambda-variable (name binding))
        for sub = (term binding)
        do (setf term (substitute-avoiding-capture term var sub))
        finally (return term)))

(defun reduce-and-print-terms (terms &optional (stream *standard-output*))
  (let (last)
    (map nil (lambda (term)
               (setf last (reduce-term term))
               (fresh-line stream)
               (print-term last stream))
         terms)
    last))

(defun run-lambda-program (file &optional (stream *standard-output*))
  (let* ((source (uiop:read-file-string file))
         (scanner (make-lambda-scanner source))
         (tokens (scan-tokens scanner))
         (parser (make-lambda-parser tokens source))
         (toplevels (parse-lambda-file parser))
         (terms (remove-if #'lambda-binding-p toplevels))
         (bindings (remove-if-not #'lambda-binding-p toplevels)))
    (map-into terms (lambda (term) (substitute-lambda-bindings term bindings)) terms)
    (reduce-and-print-terms terms stream)))

(defun run-combinator-program (file &optional (stream *standard-output*))
  (let* ((source (uiop:read-file-string file))
         (scanner (make-combinator-scanner source))
         (tokens (scan-tokens scanner))
         (parser (make-combinator-parser tokens source))
         (toplevels (parse-combinator-file parser))
         (terms (remove-if #'combinator-binding-p toplevels))
         (*combinator-bindings*
           (loop with table = (make-hash-table :test #'equal)
                 for binding across (remove-if-not #'combinator-binding-p toplevels)
                 do (setf (gethash (name binding) table) binding)
                 finally (return table))))
    (reduce-and-print-terms terms stream)))
