(defpackage #:ski
  (:use #:cl)
  (:shadow #:variable)
  (:export
   #:term
   #:term-p
   #:application
   #:application-p
   #:left
   #:right
   #:make-variable-name-generator
   #:generate-name
   #:name
   #:variable
   #:variable-p
   #:same-variable-p
   #:occurs-free-p
   #:print-term
   #:reduce-term
   #:term-equal
   #:combinator-term
   #:combinator-term-p
   #:combinator
   #:combinator-p
   #:define-combinator
   #:get-combinator
   #:arity
   #:make-combinator-application
   #:combinator-application-p
   #:make-combinator-variable
   #:combinator-variable-p
   #:combinator-driver-loop
   #:lambda-term
   #:lambda-term-p
   #:make-lambda-abstraction
   #:lambda-abstraction-p
   #:body
   #:make-lambda-application
   #:lambda-application-p
   #:make-lambda-variable
   #:lambda-variable-p
   #:free-variables
   #:bound-variables
   #:lambda-combinator-p
   #:*lambda-reduction-strategy*
   #:substitute-avoiding-capture
   #:lambda-driver-loop
   #:sk->goedel
   #:goedel->sk
   #:natural->church
   #:church->natural
   #:natural->barendregt
   #:barendregt->natural
   #:combinator->lambda
   #:combinator->ski
   #:lambda->ski
   #:lambda->sk
   #:parse-combinator-term
   #:parse-lambda-term
   #:build-lambda-program
   #:run-lambda-program
   #:run-combinator-program))
